import Head from 'next/head'
import Link from 'next/link'
import { 
    AiFillLinkedin,
    AiFillInstagram,
    AiFillGithub,
    AiFillMail,
} from 'react-icons/ai'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={'h-20'}></div>
      <div className={'w-full h-fit text-center'}>
        <div className={'max-w-[1240px] w-full h-full mx-auto p-2 flex justify-center items-center'}>
            <div className={''}>
                <p className={'uppercase text-sm tracking-widest text-[#D4AF37]'}>Teams and dreams may coexist.</p>
                <h1 className={'py-4 text-white'}>
                    Hi, I am <span className={'text-[#D4AF37]'}>Vutlhari Chauke</span>
                </h1>
                <h2 className={'py-4 text-white'}>
                    Full-Stack Developer | Passionate about Building Solutions
                </h2>
                <p className={'py-4 text-white max-w-[70%] m-auto'}>
                    As a self-taught developer, I’ve grown my skills by taking on real-world projects, 
                    diving into both front-end and back-end technologies. I’m driven by curiosity, 
                    constantly seeking to improve and stay up-to-date with the ever-evolving tech landscape.
                </p>
                <p className={'py-4 text-white max-w-[70%] m-auto'}>
                    I believe that tech should be accessible and user-friendly. With every project I take on, 
                    my goal is to deliver solutions that not only meet user needs but also create engaging, 
                    intuitive experiences. Whether working independently or in teams, I value collaboration 
                    and believe that diversity in ideas leads to better outcomes.
                </p>
                <p className={'py-4 text-white max-w-[70%] m-auto'}>
                    Throughout my journey, I’ve had the privilege of working alongside other talented individuals. 
                    It’s through teamwork that we bring ideas to life, and I’m always open to learning from others, 
                    sharing knowledge, and pushing myself to achieve more. Tech is not just about building code; 
                    it's about creating impact, and that’s the mindset I carry into everything I do.
                </p>
                <div className={'flex items-center justify-between max-w-[400px] m-auto py-4'}>
                    <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'https://www.instagram.com/shalatiey23/'}><AiFillInstagram size={20} /></Link>
                    </div>
                    <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'https://www.linkedin.com/in/vutlhari-chauke-17b961271/'}><AiFillLinkedin size={20} /></Link>
                    </div>
                    <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'https://github.com/Shalatiey23'}><AiFillGithub size={20}/></Link>
                    </div>
                    <div className={'rounded-full shadow-lg shadow-gray-900 p-6 cursor-pointer hover:scale-110 ease-in duration-75'}>
                        <Link href={'mailto:vchauke357@gmail.com'}><AiFillMail size={20}/></Link>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
  )
}
