import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import classNames from 'classnames'

const Projects = () => {
  const router = useRouter()

  const isActive = (path) => router.pathname === path

  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={'h-20'}></div>
      <div className={'w-full'}>
        <div className={'max-w-[1240px] mx-auto px-2 py-16'}>
          <p className={'text-xl tracking-widest uppercase text-[#D4AF37] text-center font-bold'}>Projects</p>
          <h2 className={'py-4 text-center'}>What I have built</h2>
          <div className={'grid grid-cols-1 gap-8'}>

            </div>
          </div>
        </div>
    </>
  )
}

export default Projects
